# Trunk build configuration
# https://trunkrs.dev/configuration/

[build]
target = "index.html"
dist = "dist"
filehash = true
public_url = "/road-drawing/"

[watch]
watch = ["src", "index.html", "Trunk.toml"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[clean]
dist = "dist"
cargo = false
